# SPDX-License-Identifier: AGPL-3.0-only
[package]
name = "temnion-index"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
temnion-core.workspace = true
temnion-events.workspace = true
temnion-format.workspace = true
crc32fast.workspace = true

[lints]
workspace = true
